name: Workflow for CI with github actions

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm build

      - name: Launch Unit Test && Integration Test
        run: pnpm run test

      - name: Save build data
        uses: actions/upload-artifact@v4
        with:
          name: build
          if-no-files-found: error
          path: .next
