name: Tests and Deploy for Skubey

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  NextJS-Tests:
    name: Tests for Skubey
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [22.x]  # Specify the Node.js version you're using

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3 for better performance

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run Jest tests
        run: pnpm test

  Deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: NextJS-Tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Only deploy on push to main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25  # Using official Vercel action
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: '--prod'