name: Tests and Deploy for Skubey

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  NextJS-Tests:
    name: Tests for Skubey
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          pnpm install

      - name: Run Jest tests
        run: pnpm test

  Deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: NextJS-Tests
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          pnpm install

      - name: Deploy to Vercel
        run: vercel --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}